### ISSUE TITLE
Login didnt work

### ISSUE THREAD

**Issue by chinnaiyanvignesh** [lucatacconi/crunz-ui#10]
**After login - Page redirects back to login page**
I have configured the server with necessary PHP modules and configured the httpd conf properly.

**Comment by lucatacconi** [comment]
Hi Chinnaiyanvignesh,
i need some informations to help you.

Have you installed Crunz-ui in your machine or in a virtual machine?
Is Crunz-ui served by Apache server or Xampp?
Which OS are you using? 
If you are using Xampp do you have a PHP installed on your machine too?

**Comment by chinnaiyanvignesh** [comment]
Hi lucatacconi,

Thanks for the quick reply.

I have installed Crunz-UI on AWS EC2, OS - Amazon Linux 2 (Centos)

I have CRUNZ installed after trying CRUNZ-UI, crunz worked on my server.

I dont see any error in CRUNZ-UI, only issue is when i try to login with the default username and password - It get redirected to Login page itself.

Thanks for SUPPORT.

**Comment by lucatacconi** [comment]
Hi Chinnaiyanvignesh,
please confirm that no error messages appear and that, even using the Chrome or Firefox developer tool, no errors appear in console section.

I would ask you first of all to check the expiration date of the login with which you tested the access. You must also check the configuration relating to the duration of the session. I already know that the problem is not that but for the sake of scruple I ask you.

The problem you encountered could instead be related to the configuration of the time and time zone of the server and if the time zone and time are different on your PC. Cruz-ui has a mechanism whereby, if the user's session has expired, the user first sees an error message that warns him of the expired session and then is sent back to the login page.

However, an error situation similar to the one you describe happened to me, precisely due to the difference in the times on the server and on my PC used to access the web interface. In that case, following a successful login, I would see the dashboard for a fraction of a second and then return to login without visible errors.

Can you check if the time is correctly configured?
In Ubuntu server usually I use this sequence of commands (the last one is only to check date and time configured)
```
sudo apt-get install ntp
sudo timedatectl set-timezone FAVORITE_TIMEZONE
sudo service ntp restart
timedatectl
```
Whit a Centos Server i suppose you have to use yum -y install ntp.

I await your news.

**Comment by lucatacconi** [comment]
I forgot .. if the custom Session Duration is not configured then the default session duration is 2 hours

**Comment by chinnaiyanvignesh** [comment]
Hi Lucatacconi,

I did check everything mentioned on your previous timezone message, it didnt work.

After that i have modified the SESSION_DURATION in .env file from 2 hours to 24 hours, SUCCESS - It worked and i can login and see dashboard page.

Thanks for the help.

**Comment by lucatacconi** [comment]
I have added notes for solving your problem in the latest release
